---
problem_steps: [null, null, "costmap_bundle_adjustment"]
feature_config:
    sparse : True
    pyr_scales : [1.0]
    max_edge : 1600
    patch_size : 12
    device : "cuda"
    dtype : "half"
    store_h5: false
    load_h5_if_exists: false
    h5_format: "chunked"
extractor: "s2dnet"
interpolation_config:
    nodes: [[0.0,0.0]] #default: take pointwise nodes.
    type: "bicubic"
    l2_normalize: true
    ncc_normalize: false #only makes sense if n_nodes > 1 
ka_setup:
    level_order: "all" #use all featuremaps obtained and optimize them in reverse (coarse-to-fine)
    num_threads: 16 #outer parallelism
    max_tracks_per_problem: 10
    ka_options:
        loss:
            name: "cauchy"
            params: [0.25] # since losses can take different number of params, we take them from the list in order.
        num_solver_threads: 1 #nested parallelism
        solver_options:
            max_num_iterations: 100
            minimizer_progress_to_stdout: false
            max_num_consecutive_invalid_steps: 10
            function_tolerance: 0.0
            gradient_tolerance: 0.0
            parameter_tolerance: 1.0e-5
            inner_iteration_tolerance: 1.0e-5
            use_inner_iterations: false
            update_state_every_iteration: false
            use_nonmonotonic_steps: false
        root_regularize_weight: -1.0 # <= 0.0 is no regularization
        print_summary: false
        bound: 20.0 #-1 is automatic
ba_setup:
    repeats: 1
    num_threads: 16 # <1 equals to all threads
    level_order: "all" #only optimize on a subset of obtained levels
    max_tracks_per_problem: 10
    reference_config:
        loss:
            name: "cauchy"
            params: [0.25]
        compute_all_scores: false
        iters: 100
        compute_offsets3D: false
    costmap_config:
        loss:
            name: "trivial"
            params: []
        as_gradientfield: true
        compute_cross_derivatives: false
    ba_options:
        loss:
            name: "cauchy"
            params: [0.25]
        solver_options:
            function_tolerance: 0.0
            gradient_tolerance: 0.0
            parameter_tolerance: 0.0
            minimizer_progress_to_stdout: true
            max_num_iterations: 10
            max_linear_solver_iterations: 200
            max_num_consecutive_invalid_steps: 10
            max_consecutive_nonmonotonic_steps: 10
            use_inner_iterations: true
        print_summary: true
        refine_focal_length: false
        refine_principal_point: false
        refine_extra_params: false
        refine_extrinsics: false    
    
    
    
