---
problem_steps: [null, "triangulation", null]
feature_config:
    sparse : True
    pyr_scales : [1.0]
    max_edge : 1600
    patch_size : 16
    device : "cpu"
    dtype : "half"
    store_h5: false
    load_h5_if_exists: true
extractor: "image"
    

    
    
    
    
